
title: Aaron Fischer
email: amfischer21@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a full-stack web developer who works mostly with the PHP and JavaScript
  ecosystems. I enjoy creating DRY and readable code that is easy for myself 
  and others to understand.
twitter_username: amfische
github_username:  amfische

collections:
  projects:
    output: true

defaults:
- scope:
    type: projects
  values:
    layout: navbar
    permalink: "/projects/:title"

sass:
  sass_dir: /assets/_sass

# assets:
#   sources:
#     - assets/_sass
#   autoprefixer:
#     browsers:
#       - "last 2 versions"
#       - "IE > 9"

# Build settings
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - old-code

timezone: America/Phoenix
