
title: Aaron Fischer
email: amfischer21@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a full-stack web developer who works mostly with the PHP and JavaScript
  ecosystems. I enjoy creating DRY and readable code that is easy for myself 
  and others to understand.
twitter_username: amfische
github_username:  amfische

collections:
  projects:
    output: true

defaults:
- scope:
    type: projects
  values:
    layout: navbar
    permalink: "/projects/:title"

sass:
  sass_dir: assets/_sass

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

timezone: America/Phoenix
